# Generated by Django 5.2.7 on 2025-10-10 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('kod', models.CharField(help_text='Kod ISO kraju (np. PL, FR)', max_length=3, unique=True)),
                ('kontynent', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kraj',
                'verbose_name_plural': 'Kraje',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('adres', models.CharField(blank=True, max_length=200)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10)),
                ('miasto', models.CharField(blank=True, max_length=100)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_klienta', to=settings.AUTH_USER_MODEL)),
                ('kraj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienci', to='wycieczki.kraj')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('miasto', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=200)),
                ('kategoria', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('opis', models.TextField()),
                ('udogodnienia', models.TextField(help_text='Udogodnienia w hotelu (basen, siłownia, spa, etc.)')),
                ('strona_www', models.URLField(blank=True)),
                ('kraj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotele', to='wycieczki.kraj')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotele',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='LiniaLotnicza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kod_iata', models.CharField(help_text='Kod IATA (np. LOT, LH)', max_length=3, unique=True)),
                ('strona_www', models.URLField(blank=True)),
                ('kraj_pochodzenia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linie_lotnicze', to='wycieczki.kraj')),
            ],
            options={
                'verbose_name': 'Linia lotnicza',
                'verbose_name_plural': 'Linie lotnicze',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_lotu', models.CharField(max_length=10, unique=True)),
                ('lotnisko_wylotu', models.CharField(max_length=100)),
                ('lotnisko_przylotu', models.CharField(max_length=100)),
                ('data_wylotu', models.DateTimeField()),
                ('data_przylotu', models.DateTimeField()),
                ('czas_trwania', models.DurationField(help_text='Czas trwania lotu')),
                ('linia_lotnicza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loty', to='wycieczki.linialotnicza')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Loty',
                'ordering': ['data_wylotu'],
            },
        ),
        migrations.CreateModel(
            name='Wycieczka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
                ('liczba_dni', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('liczba_nocy', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('opcja_cenowa', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury')], default='STANDARD', max_length=20)),
                ('cena_za_osobe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cena_dziecko', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_liczba_osob', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('aktywna', models.BooleanField(default=True, help_text='Czy wycieczka jest aktualnie dostępna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wycieczki', to='wycieczki.hotel')),
                ('kraj_docelowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wycieczki', to='wycieczki.kraj')),
                ('lot_powrot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wycieczki_powrot', to='wycieczki.lot', verbose_name='Lot powrotny')),
                ('lot_tam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wycieczki_tam', to='wycieczki.lot', verbose_name='Lot w jedną stronę')),
            ],
            options={
                'verbose_name': 'Wycieczka',
                'verbose_name_plural': 'Wycieczki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OCZEKUJACA', 'Oczekująca'), ('POTWIERDZONA', 'Potwierdzona'), ('OPLACONA', 'Opłacona'), ('ANULOWANA', 'Anulowana'), ('ZAKONCZONA', 'Zakończona')], default='OCZEKUJACA', max_length=20)),
                ('liczba_doroslich', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('liczba_dzieci', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cena_calkowita', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('zaliczka', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pozostalo_do_zaplaty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('data_potwierdzenia', models.DateTimeField(blank=True, null=True)),
                ('data_oplaty', models.DateTimeField(blank=True, null=True)),
                ('uwagi', models.TextField(blank=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='wycieczki.klient')),
                ('wycieczka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='wycieczki.wycieczka')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-data_rezerwacji'],
            },
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(help_text='Ocena od 1 do 5 gwiazdek', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('ocena_hotelu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ocena_lotu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ocena_obslugi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('zweryfikowana', models.BooleanField(default=False, help_text='Czy opinia została zweryfikowana przez administratora')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='wycieczki.klient')),
                ('rezerwacja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinia', to='wycieczki.rezerwacja')),
                ('wycieczka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='wycieczki.wycieczka')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
                'ordering': ['-data_dodania'],
                'unique_together': {('wycieczka', 'klient')},
            },
        ),
    ]
